---
title: "Degradation Simulations"
author: "Benjamin Jack"
date: "5/3/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cowplot)
library(gtools)
```


```{r cars}
labels <- read_csv("../output/id_map.csv")
read_sim <- function(path) {
  raw_data <- read_tsv(path) 
  labeled_data <- right_join(raw_data, labels, by = c("species" = "pysinthe")) %>% 
    mutate(time = round(time)) # round times to whole seconds
}
# data <- read_sim("../src/python/degrade_test4_counts.tsv")
data <- read_sim("../data/050718/degrade_test3_counts.tsv")

bar_sim <- filter(data, !is.na(class), time %in% c(320, 1500)) %>%
  left_join(labels)

bar_sim_plot <- ggplot(bar_sim, aes(x=factor(gene_number, unique(mixedsort(gene_number))), y=transcript, fill=factor(class))) +
  geom_bar(stat = "identity") +
  facet_wrap(~time, scales = "free", ncol = 1) +
  theme(legend.position = "none") +
  labs(x="gene", y="count")

bar_sim_plot

save_plot("figures/sim_degradation2.pdf", bar_sim_plot, base_width = 8, base_height = 6)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
