---
title: "Toy Degradation Models"
author: "Benjamin Jack"
date: "9/26/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cowplot)

cbPalette <- c("#CC79A7", "#56B4E9", "#E69F00", "#F0E442", "#0072B2", "#D55E00", "#009E73", "#999999")
```

## Toy model with RNAse site and promoters

```{r}
data <- read_tsv("../data/simulation/three_genes/three_genes_rnase.tsv") %>%
  mutate(species = str_replace_all(species, "protein", ""))
data %>% filter(species %in% c("X", "Y", "Z")) -> data
line_plot <- ggplot(data, aes(x = time, y = transcript, color=species)) + 
  geom_line()  + 
  theme(legend.position="none") +
  scale_color_manual(values = cbPalette)
bar_plot_early <- ggplot(data %>% filter(time > 99, time < 100), aes(fill=species, x=species, y=transcript)) +
  geom_bar(stat="identity") + 
  theme(legend.position="none") +
  scale_y_continuous(expand=c(0,0)) +
  scale_fill_manual(values = cbPalette) +
  xlab("gene")
bar_plot_late <- ggplot(data %>% filter(time > 239, time < 240), aes(fill=species, x=species, y=transcript)) + 
  geom_bar(stat="identity") + 
  scale_y_continuous(expand=c(0,0)) +
  scale_fill_manual("gene", values = cbPalette) +
  xlab("gene")
final_plot <- plot_grid(line_plot, bar_plot_early, bar_plot_late, ncol=3, 
                        rel_widths = c(1, 1, 1.3), align = "h", labels="AUTO")

final_plot

save_plot("./figures/three_genes_rnase_prom.pdf", final_plot, ncol = 2, base_width = 5.5)
```

## Toy model with just promoters

```{r}
data <- read_tsv("../data/simulation/three_genes/three_genes_prom.tsv") %>%
  mutate(species = str_replace_all(species, "protein", ""))
data %>% filter(species %in% c("X", "Y", "Z")) -> data
line_plot <- ggplot(data, aes(x = time, y = transcript, color=species)) + 
  geom_line()  + 
  scale_color_manual(values=cbPalette) +
  theme(legend.position="none")
bar_plot_early <- ggplot(data %>% filter(time > 99, time < 100), aes(fill=species, x=species, y=transcript)) +
  geom_bar(stat="identity") + 
  theme(legend.position="none") +
  scale_y_continuous(expand=c(0,0)) +
  scale_fill_manual(values=cbPalette) +
  xlab("gene")
bar_plot_late <- ggplot(data %>% filter(time > 239, time < 240), aes(fill=species, x=species, y=transcript)) + 
  geom_bar(stat="identity") + 
  scale_y_continuous(expand=c(0,0)) +
  scale_fill_manual("gene", values=cbPalette) +
  xlab("gene")
final_plot <- plot_grid(line_plot, bar_plot_early, bar_plot_late, ncol=3, 
                        rel_widths = c(1, 1, 1.3), align = "h", labels="AUTO")

final_plot

save_plot("./figures/three_genes_prom.pdf", final_plot, ncol = 2, base_width = 5.5)
```